name: Fuzzing
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - FuzzServerChecksum
          - FuzzBuild
          - FuzzParseSID
          - FuzzParseHashInput
          - FuzzEncryptRC4
    steps:
      - uses: actions/checkout@11bd71901abe5b8200e2588b02e1923d7c00a5e3 # v4.2.2
        with:
          persist-credentials: false

      - uses: actions/setup-go@f111f3307d8850f799b82f0e7b6506e09454a7d2 # v5.3.0
        with:
          go-version: '1.24'

      - name: Run fuzz test
        run: |
          go test -fuzz=${{ matrix.target }} -fuzztime=5m \
            -run='^$' ./...
